pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Clonar el repositorio
                git 'https://github.com/Carlos2002234/CI-CD.git'
            }
        }
        stage('Test') {
            steps {
                // Instalar dependencias
                sh 'pip install -r Hello-World/requirements.txt'
                // Instalar pytest
                sh 'pip install pytest'
                // Ejecutar pruebas con pytest
                sh 'pytest Hello-World/tests/'
            }
        }
    }
}
